CREATE TABLE IF NOT EXISTS restaurante.cliente
(
    ID              BIGSERIAL    NOT NULL,
    NOME            VARCHAR(128) NOT NULL,
    ENDERECO        VARCHAR(128) NOT NULL,
    DATA_REGISTRO   TIMESTAMP,
    TELEFONE        VARCHAR(128),
    CELULAR         VARCHAR(128) NOT NULL,
    CPF             VARCHAR(128) NOT NULL,
    DATA_NASCIMENTO TIMESTAMP,
    CONSTRAINT pk_cliente PRIMARY KEY (ID)
);
