CREATE TABLE IF NOT EXISTS restaurante.cliente
(
    ID              BIGSERIAL    NOT NULL,
    NOME            VARCHAR(128) NOT NULL,
    ENDERECO        VARCHAR(128) NOT NULL,
    DATA_REGISTRO   TIMESTAMP,
    TELEFONE        VARCHAR(128),
    CELULAR         VARCHAR(128) NOT NULL,
    CPF             VARCHAR(128) NOT NULL,
    DATA_NASCIMENTO TIMESTAMP,
    ID_PEDIDO BIGSERIAL,
    CONSTRAINT pk_cliente PRIMARY KEY (ID),
    CONSTRAINT fk_cliente_pedido FOREIGN KEY (ID_PEDIDO)
        REFERENCES restaurante.pedido

);
