server:
  port: 8080
spring:
  flyway:
    enabled: true
    baseline-on-migrate: true
  datasource:
    url: jdbc:postgresql://localhost:5432/restaurante
    username: postgres
    password: postgres
